apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        {{ .Values.key }}: {{ .Values.value }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.app }}
          ports:
            - containerPort: 80
